import pandas as pd

# 1 - Colocar esses dados em um formato de leitura para vetorização(Pandas)
# 2 - Criar uma função para que esses dados possam ser invocados

# Dataset de Doenças completo e com os dados limpos
dados = [
    # Alzheimer (15 exemplos)
    ("esquecimento constante confusão perda de referências com fraqueza", "alzheimer"),
    ("esquecimento confusão perda de noção de tempo e lugar", "alzheimer"),
    ("esquecimento confusão perda de noção de tempo e lugar", "alzheimer"),
    ("perda de memória progressiva confusão dificuldade de orientacão", "alzheimer"),
    ("problemas de memória confusão mental desorientação temporal", "alzheimer"),
    ("problemas de memória confusão mental desorientação temporal", "alzheimer"),
    ("esquecimento confusão perda de noção de tempo e lugar", "alzheimer"),
    ("problemas de memória confusão dificuldade de localização", "alzheimer"),
    ("perda de memória confusão mental desorientação", "alzheimer"),
    ("esquecimento constante confusão perda de referências com fraqueza", "alzheimer"),
    ("esquecimento constante confusão perda de referências", "alzheimer"),
    ("perda de memória confusão frequente dificuldade de localização", "alzheimer"),
    ("problemas de memória severos confusão mental desorientação", "alzheimer"),
    ("problemas de memória severos confusão mental desorientação", "alzheimer"),
    ("esquecimento frequente confusão perda de orientação", "alzheimer"),

    # Anemia_falciforme (15 exemplos)
    ("cansaco extremo dor articular severa crises dolorosas e mal estar geral", "anemia_falciforme"),
    ("cansaço extremo dor articular severa crises dolorosas", "anemia_falciforme"),
    ("cansaço extremo dor articular episódios dolorosos e dor de cabeça", "anemia_falciforme"),
    ("cansaço severo dor articular crises de dor intensa", "anemia_falciforme"),
    ("cansaço severo dor articular intensa dor em crises", "anemia_falciforme"),
    ("fadiga severa dor nas juntas dor em episódios", "anemia_falciforme"),
    ("cansaço que não passa dor articular crises álgicas", "anemia_falciforme"),
    ("fadiga severa dor nas juntas dor em episódios", "anemia_falciforme"),
    ("cansaço extremo dor articular severa crises dolorosas com fraqueza", "anemia_falciforme"),
    ("fadiga severa dor nas articulações crises de dor", "anemia_falciforme"),
    ("cansaço extremo dor articular episódios dolorosos", "anemia_falciforme"),
    ("cansaco severo dor articular intensa dor em crises", "anemia_falciforme"),
    ("fadiga constante dor nas juntas crises dolorosas", "anemia_falciforme"),
    ("fadiga severa dor nas juntas dor em episódios", "anemia_falciforme"),
    ("cansaço que não passa dor articular crises álgicas acompanhado de tontura", "anemia_falciforme"),

    # Artrite_reumatoide (15 exemplos)
    ("dor articular crônica juntas inchadas rigidez matinal", "artrite_reumatoide"),
    ("articulações inflamadas dor constante rigidez", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento com fraqueza", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento", "artrite_reumatoide"),
    ("dor nas articulações inchaço nas juntas rigidez matinal e mal estar geral", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar e dor de cabeça", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar", "artrite_reumatoide"),
    ("articulaçoes inflamadas dor constante rigidez", "artrite_reumatoide"),
    ("articulações dolorosas inchaço persistente rigidez", "artrite_reumatoide"),
    ("dor articular juntas inchadas dificuldade para se mover", "artrite_reumatoide"),
    ("dor nas juntas inchaco articular rigidez ao acordar", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular dificuldade de movimento e perda de apetite", "artrite_reumatoide"),
    ("articulações rígidas e doloridas inchaço persistente", "artrite_reumatoide"),
    ("dor nas juntas inchaço articular rigidez ao acordar e perda de apetite", "artrite_reumatoide"),
    ("dor articular juntas inchadas dificuldade para se mover com fraqueza", "artrite_reumatoide"),

    # Diabetes_tipo1 (15 exemplos)
    ("sede constante micção frequente perda de peso rápida", "diabetes_tipo1"),
    ("muita sede urinar muito emagrecimento", "diabetes_tipo1"),
    ("sede excessiva poliúria perda de peso inexplicável", "diabetes_tipo1"),
    ("muita sede urina frequente emagrecimento súbito", "diabetes_tipo1"),
    ("sede excessiva urina frequente perda de peso e mal estar geral", "diabetes_tipo1"),
    ("muita sede urina frequente emagrecimento súbito", "diabetes_tipo1"),
    ("sede excessiva urina frequente perda de peso", "diabetes_tipo1"),
    ("sede intensa micção excessiva perda de peso e mal estar geral", "diabetes_tipo1"),
    ("sede excessiva poliúria perda de peso inexplicável", "diabetes_tipo1"),
    ("sede constante urinar muito emagrecimento rápido", "diabetes_tipo1"),
    ("sede intensa urina em excesso emagrecimento súbito", "diabetes_tipo1"),
    ("sede constante urinar mt emagrecimento rápido acompanhado de tontura", "diabetes_tipo1"),
    ("muita sede frequência urinária aumentada emagrecimento", "diabetes_tipo1"),
    ("sede constante urinar muito emagrecimento rápido", "diabetes_tipo1"),
    ("muita sede urina frequente emagrecimento súbito e perda de apetite", "diabetes_tipo1"),

    # Doenca_crohn (15 exemplos)
    ("cólicas abdominais intensas diarreia sanguinolenta", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento e perda de apetite", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza acompanhado de tontura", "doenca_crohn"),
    ("dor abdominal severa diarreia crônica fadiga", "doenca_crohn"),
    ("dor no abdômen fezes líquidas perda de peso rápida", "doenca_crohn"),
    ("cólicas abdominais intensas diarreia sanguinolenta com fraqueza", "doenca_crohn"),
    ("cólicas abdominais intensas diarreia sanguinolenta", "doenca_crohn"),
    ("dor abdominal severa diarreia crônica fadiga", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento com fraqueza", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento", "doenca_crohn"),
    ("cólicas abdominais diarreia persistente perda de apetite e mal estar geral", "doenca_crohn"),
    ("cólicas fortes diarreia com muco emagrecimento", "doenca_crohn"),
    ("dor no abdômen fezes líquidas perda de peso rápida", "doenca_crohn"),
    ("dor na região abdominal diarreia frequente fraqueza e dor de cabeça", "doenca_crohn"),

    # Doenca_lyme (15 exemplos)
    ("febre baixa cansaço dor no corpo manchas na pele", "doenca_lyme"),
    ("febre baixa cansaço constante dor no corpo manchas", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas e mal estar geral", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas acompanhado de tontura", "doenca_lyme"),
    ("febre baixa cansaço constante dor no corpo manchas e perda de apetite", "doenca_lyme"),
    ("febre intermitente fadiga dor muscular erupçao acompanhado de tontura", "doenca_lyme"),
    ("febre baixa cansaço severo dor no corpo manchas cutâneas acompanhado de tontura", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupçoes", "doenca_lyme"),
    ("febre fadiga dor muscular erupção cutânea com fraqueza", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupções", "doenca_lyme"),
    ("febre intermitente fadiga dor muscular erupção acompanhado de tontura", "doenca_lyme"),
    ("febre intermitente cansaço dor corporal lesões cutâneas", "doenca_lyme"),
    ("febre fadiga dor muscular erupção cutânea e mal estar geral", "doenca_lyme"),
    ("febre persistente fadiga severa dor muscular erupções acompanhado de tontura", "doenca_lyme"),
    ("febre baixa cansaço constante dor no corpo manchas", "doenca_lyme"),

    # Doenca_wilson (15 exemplos)
    ("cansaço dor na barriga tremor problemas no fígado", "doenca_wilson"),
    ("cansaço dor na região abdominal tremor hepatopatia", "doenca_wilson"),
    ("fadiga constante dor abdominal tremores hepatopatia", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática e mal estar geral", "doenca_wilson"),
    ("cansaço dor na barriga tremor problemas no fígado", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática", "doenca_wilson"),
    ("cansaço constante dor no abdômen tremor problemas hepáticos", "doenca_wilson"),
    ("fadiga dor abdominal tremores problemas hepáticos", "doenca_wilson"),
    ("cansaço dor na barriga tremor problemas no fígado", "doenca_wilson"),
    ("cansaço dor na barriga tremor problemas no fígado", "doenca_wilson"),
    ("cansaço severo dor na barriga tremor disfunção hepática", "doenca_wilson"),
    ("cansaco crônica dor abdominal tremores disfunção do fígado", "doenca_wilson"),
    ("fadiga extrema dor abdominal tremores hepatopatia", "doenca_wilson"),
    ("cansaço constante dor no abdômen tremor problemas hepáticos acompanhado de tontura", "doenca_wilson"),

    # Esclerose_lateral (15 exemplos)
    ("braços sem força fala difícil atrofia muscular", "esclerose_lateral"),
    ("braços fracos problemas na fala contrações musculares", "esclerose_lateral"),
    ("perda de forca muscular dificuldade para engolir e dor de cabeça", "esclerose_lateral"),
    ("dificuldade para levantar os bracos fala alterada", "esclerose_lateral"),
    ("perda de força fala lenta rigidez muscular com fraqueza", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de forca nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de força muscular dificuldade para engolir", "esclerose_lateral"),
    ("dificuldade para levantar os braços fala alterada", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("dificuldade para levantar os braços fala alterada", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos", "esclerose_lateral"),
    ("perda de força nos membros fala arrastada espasmos e perda de apetite", "esclerose_lateral"),
    ("dificuldade para mover os bracos fala prejudicada tremores", "esclerose_lateral"),

    # Esclerose_multipla (15 exemplos)
    ("fadiga persistente perda de força visão dupla formigamento acompanhado de tontura", "esclerose_multipla"),
    ("fadiga crônica coordenação prejudicada visão turva", "esclerose_multipla"),
    ("fadiga fraqueza nas pernas visão turva formigamento", "esclerose_multipla"),
    ("cansaco severa fraqueza muscular visao dupla dormência", "esclerose_multipla"),
    ("fadiga fraqueza nas pernas visão turva formigamento", "esclerose_multipla"),
    ("cansaço severo fraqueza muscular problemas visuais tontura", "esclerose_multipla"),
    ("cansaco persistente perda de forca visão dupla formigamento acompanhado de tontura", "esclerose_multipla"),
    ("cansaço extremo pernas fracas visão embaçada formigamento", "esclerose_multipla"),
    ("fadiga persistente perda de força visão dupla formigamento e dor de cabeça", "esclerose_multipla"),
    ("cansaco persistente perda de força visão dupla formigamento", "esclerose_multipla"),
    ("fadiga crônica coordenação prejudicada visão turva", "esclerose_multipla"),
    ("cansaço severo fraqueza muscular problemas visuais tontura acompanhado de tontura", "esclerose_multipla"),
    ("fadiga persistente perda de força visão dupla formigamento", "esclerose_multipla"),
    ("fadiga crônica coordenacão prejudicada visão turva", "esclerose_multipla"),
    ("fadiga perda de equilíbrio problemas de visão dormência", "esclerose_multipla"),

    # Febre_maculosa (15 exemplos)
    ("temperatura alta dor nos músculos cansaço que nao passa", "febre_maculosa"),
    ("febre alta dor no corpo todo cansaço extremo", "febre_maculosa"),
    ("febre persistente dor muscular generalizada erupçao cutânea", "febre_maculosa"),
    ("temperatura alta dor nos músculos cansaço que não passa", "febre_maculosa"),
    ("febre de 39°c dor nas costas náusea e vômito", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas cansaco severa com fraqueza", "febre_maculosa"),
    ("temperatura elevada dor generalizada náusea", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas fadiga severa com fraqueza", "febre_maculosa"),
    ("temperatura elevada dores musculares intensas fadiga severa", "febre_maculosa"),
    ("febre persistente fadiga extrema erupcões na pele", "febre_maculosa"),
    ("febre de 39°c dor nas costas náusea e vômito", "febre_maculosa"),
    ("temperatura alta dor nos músculos cansaço que não passa", "febre_maculosa"),
    ("febre alta dor no corpo todo cansaço extremo", "febre_maculosa"),
    ("dor de cabeça intensa febre alta dor muscular", "febre_maculosa"),
    ("febre persistente fadiga extrema erupções na pele", "febre_maculosa"),

    # Fibromialgia (15 exemplos)
    ("dor no corpo todo cansaço constante dificuldade para dormir", "fibromialgia"),
    ("dores musculares difusas fadiga severa sono ruim", "fibromialgia"),
    ("dor muscular difusa cansaço severo dificuldades do sono acompanhado de tontura", "fibromialgia"),
    ("dor no corpo todo cansaço constante dificuldade para dormir", "fibromialgia"),
    ("dor em múltiplos pontos fadiga crônica insônia severa", "fibromialgia"),
    ("dor corporal generalizada cansaco persistente sono fragmentado", "fibromialgia"),
    ("dor em vários pontos do corpo cansaço extremo insônia e perda de apetite", "fibromialgia"),
    ("dor muscular generalizada fadiga crônica insônia e perda de apetite", "fibromialgia"),
    ("dor generalizada cansaço que não melhora problemas para dormir", "fibromialgia"),
    ("dor muscular generalizada cansaco crônica insônia", "fibromialgia"),
    ("dor muscular generalizada fadiga crônica insônia acompanhado de tontura", "fibromialgia"),
    ("dor muscular generalizada fadiga crônica insônia e perda de apetite", "fibromialgia"),
    ("dor no corpo todo cansaço constante dificuldade para dormir e perda de apetite", "fibromialgia"),
    ("dor muscular difusa cansaço severo dificuldades do sono e dor de cabeça", "fibromialgia"),
    ("dor no corpo todo cansaço constante dificuldade para dormir acompanhado de tontura", "fibromialgia"),

    # Hipertireoidismo (15 exemplos)
    ("emagrecimento rápido taquicardia ansiedade constante e mal estar geral", "hipertireoidismo"),
    ("perda de peso palpitações frequentes nervosismo", "hipertireoidismo"),
    ("emagrecimento súbito batimentos acelerados ansiedade", "hipertireoidismo"),
    ("emagrecimento rápido taquicardia ansiedade constante e dor de cabeça", "hipertireoidismo"),
    ("emagrecimento palpitações estado de nervosismo", "hipertireoidismo"),
    ("perda de peso inexplicável coração acelerado agitação", "hipertireoidismo"),
    ("emagrecimento súbito coração disparado ansiedade acompanhado de tontura", "hipertireoidismo"),
    ("perda de peso inexplicável coracão acelerado agitacão e mal estar geral", "hipertireoidismo"),
    ("emagrecimento súbito coraçao disparado ansiedade", "hipertireoidismo"),
    ("emagrecimento palpitações estado de nervosismo e mal estar geral", "hipertireoidismo"),
    ("emagrecimento rápido taquicardia ansiedade constante e mal estar geral", "hipertireoidismo"),
    ("emagrecimento rápido taquicardia ansiedade constante", "hipertireoidismo"),
    ("perda de peso rápida batimentos irregulares agitação", "hipertireoidismo"),
    ("perda de peso palpitações frequentes nervosismo e perda de apetite", "hipertireoidismo"),
    ("perda de peso inexplicável coração acelerado agitação", "hipertireoidismo"),

    # Hipotireoidismo (15 exemplos)
    ("fadiga severa obesidade frieza excessiva", "hipotireoidismo"),
    ("cansaço extremo obesidade progressiva sensação de frio", "hipotireoidismo"),
    ("cansaco severo aumento de peso frio excessivo acompanhado de tontura", "hipotireoidismo"),
    ("cansaco crônica aumento de peso inexplicável intolerância ao frio", "hipotireoidismo"),
    ("cansaço extremo ganho de peso inexplicável sensibilidade ao frio", "hipotireoidismo"),
    ("cansaço que não passa ganho de peso rápido frio constante e dor de cabeça", "hipotireoidismo"),
    ("cansaço extremo ganho de peso inexplicável sensibilidade ao frio e dor de cabeça", "hipotireoidismo"),
    ("fadiga constante obesidade intolerância ao frio", "hipotireoidismo"),
    ("fadiga crônica aumento de peso inexplicável intolerância ao frio acompanhado de tontura", "hipotireoidismo"),
    ("fadiga constante obesidade intolerância ao frio e dor de cabeça", "hipotireoidismo"),
    ("cansaço severo aumento de peso frio excessivo acompanhado de tontura", "hipotireoidismo"),
    ("cansaco extremo ganho de peso inexplicável sensibilidade ao frio e perda de apetite", "hipotireoidismo"),
    ("cansaço constante aumento de peso sensibilidade ao frio", "hipotireoidismo"),
    ("fadiga crônica aumento de peso inexplicável intolerância ao frio", "hipotireoidismo"),
    ("fadiga severa obesidade frieza excessiva", "hipotireoidismo"),

    # Lupus (15 exemplos)
    ("dor articular fadiga crônica sensibilidade ao sol com fraqueza", "lupus"),
    ("juntas doloridas cansaço que não passa manchas na face", "lupus"),
    ("dor articular fadiga crônica sensibilidade ao sol", "lupus"),
    ("dor nas articulações cansaco extrema problemas de pele", "lupus"),
    ("dor nas juntas fadiga que não melhora erupção facial", "lupus"),
    ("dor articular fadiga crônica sensibilidade ao sol e mal estar geral", "lupus"),
    ("fadiga constante dor nas articulações sensibilidade à luz", "lupus"),
    ("dor articular fadiga crônica sensibilidade ao sol", "lupus"),
    ("dor articular generalizada fadiga severa erupções cutâneas", "lupus"),
    ("articulações rígidas cansaço constante fotossensibilidade", "lupus"),
    ("juntas doloridas cansaço que não passa manchas na face", "lupus"),
    ("dor nas juntas fadiga que nao melhora erupçao facial com fraqueza", "lupus"),
    ("cansaço extremo articulações inchadas fotofobia", "lupus"),
    ("articulações rígidas cansaço constante fotossensibilidade e perda de apetite", "lupus"),
    ("dor articular generalizada fadiga severa erupções cutâneas", "lupus"),

    # Miastenia_gravis (15 exemplos)
    ("perda de força cansaço diplopia problemas de deglutição", "miastenia_gravis"),
    ("perda de força cansaço extremo diplopia problemas para engolir", "miastenia_gravis"),
    ("fraqueza muscular fadiga severa visão dupla dificuldade para engolir", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas para engolir", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas de deglutição", "miastenia_gravis"),
    ("perda de força cansaço diplopia problemas para engolir", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição e perda de apetite", "miastenia_gravis"),
    ("fraqueza nos músculos fadiga severa visão dupla disfagia com fraqueza", "miastenia_gravis"),
    ("perda de forca cansaco diplopia problemas para engolir", "miastenia_gravis"),
    ("fraqueza nos músculos fadiga constante visao dupla dificuldade de deglutiçao", "miastenia_gravis"),
    ("perda de forca cansaco diplopia problemas de degluticão", "miastenia_gravis"),
    ("fraqueza muscular fadiga visão dupla dificuldade para engolir acompanhado de tontura", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição com fraqueza", "miastenia_gravis"),
    ("perda de forca muscular cansaco problemas visuais dificuldade de degluticão com fraqueza", "miastenia_gravis"),
    ("perda de força muscular cansaço problemas visuais dificuldade de deglutição", "miastenia_gravis"),

    # Parkinson (15 exemplos)
    ("tremores nas mãos rigidez muscular movimentos lentos", "parkinson"),
    ("tremores nas extremidades rigidez lentidão motora e dor de cabeça", "parkinson"),
    ("tremor nas mãos rigidez corporal bradicinesia", "parkinson"),
    ("tremor nas mãos rigidez muscular instabilidade postural", "parkinson"),
    ("tremor nas mãos rigidez muscular instabilidade postural", "parkinson"),
    ("tremor nas mãos rigidez corporal bradicinesia", "parkinson"),
    ("tremor nas mãos rigidez corporal bradicinesia", "parkinson"),
    ("tremor característico músculos tensos movimentos lentos", "parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados", "parkinson"),
    ("tremor característico músculos tensos movimentos lentos e mal estar geral", "parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados e dor de cabeça", "parkinson"),
    ("tremores rigidez muscular perda de equilíbrio", "parkinson"),
    ("tremor de repouso rigidez movimentos prejudicados e mal estar geral", "parkinson"),
    ("tremor em repouso rigidez dificuldade para se mover e dor de cabeça", "parkinson"),
    ("tremor nas mãos rigidez muscular instabilidade postural e dor de cabeça", "parkinson"),

    # Porfiria (15 exemplos)
    ("dor intensa na barriga enjoo vômito confusao e perda de apetite", "porfiria"),
    ("dor abdominal intensa náusea persistente vômito confusão mental com fraqueza", "porfiria"),
    ("dor abdominal severa enjoo vômito confusao mental", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental acompanhado de tontura", "porfiria"),
    ("dor severa na barriga enjoo vômito persistente confusao", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental", "porfiria"),
    ("dor severa na barriga enjoo vômito frequente alterações cognitivas", "porfiria"),
    ("dor forte no abdômen enjoo constante vômito confusão", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental", "porfiria"),
    ("dor severa na barriga enjoo vômito frequente alteracões cognitivas e perda de apetite", "porfiria"),
    ("dor intensa no abdômen enjoo severo vômito confusão e perda de apetite", "porfiria"),
    ("dor abdominal severa náusea vômito confusão mental", "porfiria"),
    ("dor abdominal aguda enjoo vômito confusão mental e mal estar geral", "porfiria"),
    ("dor intensa no abdômen enjoo severo vômito confusão e perda de apetite", "porfiria"),
    ("dor abdominal forte náusea constante vômito alterações mentais", "porfiria"),

    # Sarcoidose (15 exemplos)
    ("cansaço severo falta de ar aos esforços tosse febre", "sarcoidose"),
    ("cansaco crônica falta de ar tosse seca persistente febre e mal estar geral", "sarcoidose"),
    ("cansaço extremo falta de ar tosse persistente febre baixa", "sarcoidose"),
    ("cansaço dispneia aos esforços tosse febre baixa", "sarcoidose"),
    ("fadiga constante dispneia tosse seca febre intermitente e dor de cabeça", "sarcoidose"),
    ("fadiga falta de ar tosse seca febre baixa", "sarcoidose"),
    ("cansaço constante dificuldade para respirar tosse febre intermitente", "sarcoidose"),
    ("fadiga severa dificuldade respiratória tosse seca febre e mal estar geral", "sarcoidose"),
    ("cansaço severo falta de ar aos esforços tosse febre e dor de cabeça", "sarcoidose"),
    ("cansaço severo falta de ar aos esforços tosse febre", "sarcoidose"),
    ("cansaço dificuldade para respirar tosse febre", "sarcoidose"),
    ("fadiga crônica falta de ar tosse seca persistente febre com fraqueza", "sarcoidose"),
    ("cansaço dificuldade para respirar tosse febre", "sarcoidose"),
    ("fadiga constante dispneia tosse seca febre intermitente", "sarcoidose"),
    ("cansaço dispneia aos esforços tosse febre baixa e dor de cabeça", "sarcoidose"),

    # Sindrome_fadiga_cronica (15 exemplos)
    ("fadiga severa crônica dor no corpo todo problemas de foco", "sindrome_fadiga_cronica"),
    ("cansaço que não alivia dor muscular difusa névoa cerebral", "sindrome_fadiga_cronica"),
    ("fadiga extrema constante dor generalizada dificuldade mental", "sindrome_fadiga_cronica"),
    ("fadiga severa crônica dor no corpo todo problemas de foco e dor de cabeça", "sindrome_fadiga_cronica"),
    ("cansaço que não alivia dor muscular difusa névoa cerebral", "sindrome_fadiga_cronica"),
    ("cansaço constante e severo dores musculares problemas cognitivos", "sindrome_fadiga_cronica"),
    ("cansaco severa crônica dor no corpo todo problemas de foco", "sindrome_fadiga_cronica"),
    ("cansaço extremo que não melhora dor muscular problemas de memória e perda de apetite", "sindrome_fadiga_cronica"),
    ("fadiga extrema dor generalizada dificuldade de concentração", "sindrome_fadiga_cronica"),
    ("fadiga extrema dor generalizada dificuldade de concentração com fraqueza", "sindrome_fadiga_cronica"),
    ("fadiga extrema constante dor generalizada dificuldade mental", "sindrome_fadiga_cronica"),
    ("cansaço extremo e persistente dor muscular confusão", "sindrome_fadiga_cronica"),
    ("cansaço extremo e persistente dor muscular confusão", "sindrome_fadiga_cronica"),
    ("fadiga severa crônica dor no corpo todo problemas de foco", "sindrome_fadiga_cronica"),
    ("cansaço constante e severo dores musculares problemas cognitivos", "sindrome_fadiga_cronica"),

    # Sindrome_sjogren (15 exemplos)
    ("secura na boca olhos ressecados cansaço dor articular crônica com fraqueza", "sindrome_sjogren"),
    ("boca seca olhos secos severos fadiga dor nas articulações", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular e dor de cabeça", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular e dor de cabeça", "sindrome_sjogren"),
    ("boca seca olhos secos severos fadiga dor nas articulações", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular", "sindrome_sjogren"),
    ("boca ressecada olhos secos crônicos fadiga dor articular e dor de cabeça", "sindrome_sjogren"),
    ("boca ressecada olhos secos fadiga constante dor articular", "sindrome_sjogren"),
    ("boca seca persistente olhos secos fadiga dor articular", "sindrome_sjogren"),
    ("secura na boca olhos ressecados cansaco extremo dor nas juntas", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular", "sindrome_sjogren"),
    ("boca seca olhos secos fadiga dor articular e perda de apetite", "sindrome_sjogren"),
    ("boca ressecada olhos secos fadiga constante dor articular", "sindrome_sjogren"),
    ("secura oral olhos ressecados cansaço constante dor articular", "sindrome_sjogren"),
    ("boca ressecada olhos secos crônicos cansaço dor articular", "sindrome_sjogren"),
]

# Criar uma funcao e colocar os dados acima em um DataFrame do Pandas
def dataset_completo():
    df = pd.DataFrame(dados, columns=['sintomas', 'diagnostico'])
    return df